# dataset cfg
dataset_type: imagenet
dataset_cfg:
  dataset_ini:
    TRAIN_BATCH_SIZE: 100
    TRAIN_NUM_WORKERS: 24
    TEST_BATCH_SIZE: 100
    TEST_NUM_WORKERS: 24
# model config
model_type: yaml
model_cfg:
  model_config_path: MNSIM/Interface/pre_train/imagenet_resnet18.yaml
# trainer config
trainer_type: SGD
trainer_cfg:
  trainer_config:
    weight_path: /home/sunhanbo/workspace/pytorch_imagenet/resnet18_mnsim_tradition.pth
    log_dir: MNSIM/Interface/pre_train/runs
    save_path: MNSIM/Interface/pre_train/zoo
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.0005
    milestones: [60, 120, 160]
    gamma: 0.1
    epochs: 200
    device: 0
    train_mode: TRADITION
    test_mode: FIX_TRAIN
    prefix: ptq
    # mode_choices, TRADITION, FIX_TRAIN, SINGLE_FIX_TEST