# dataset cfg
dataset_type: cifar100
dataset_cfg:
  dataset_ini:
    TRAIN_BATCH_SIZE: 128
    TRAIN_NUM_WORKERS: 4
    TEST_BATCH_SIZE: 100
    TEST_NUM_WORKERS: 4
# model config
model_type: yaml
model_cfg:
  model_config_path: MNSIM/Interface/examples/resnet18.yaml
# trainer config
trainer_type: Adam
trainer_cfg:
  trainer_config:
    log_dir: MNSIM/Interface/train_example/runs
    save_path: MNSIM/Interface/train_example/zoo
    # weight_path: MNSIM/Interface/zoo/cifar100_resnet18_SGD_FIX_TRAIN_FIX_TRAIN.pth
    lr: 0.001
    milestones: [150]
    gamma: 0.1
    epochs: 150
    device: 6
    train_mode: FIX_TRAIN
    test_mode: FIX_TRAIN
    # mode_choices, TRADITION, FIX_TRAIN, SINGLE_FIX_TEST