# dataset cfg
dataset_type: cifar10
dataset_cfg:
  dataset_ini:
    TRAIN_BATCH_SIZE: 128
    TRAIN_NUM_WORKERS: 4
    TEST_BATCH_SIZE: 100
    TEST_NUM_WORKERS: 4
# model config
model_type: yaml
model_cfg:
  model_config_path: MNSIM/Interface/examples/resnet18.yaml
# trainer config
trainer_type: SGD
trainer_cfg:
  trainer_config:
    log_dir: MNSIM/Interface/runs
    weight_path: MNSIM/Interface/zoo/train_resnet1_params.pth
    lr: 0.01
    weight_decay: 0.0005
    momentum: 0.9
    milestones: [30, 60]
    gamma: 0.1
    epochs: 90
    device: 0
    test_mode: SINGLE_FIX_TEST